### PR TITLE
Remove code related to the gas based staking pools

### LINKED ISSUE #143: Remove code related to the gas-based staking pools
## 📄 Context
The creation of a gas-based pool was deprecated and removed from UI. The backend (i.e. GraphQL) was deployed without the types related to the gas-based Staking Pool. Therefore, doing a good clean-up in the front end is safe.

## ✔️ Solution
Remove and/or update **included but not limited to**  logic | components | graphql model definition | stories | tests. 

## 📈 Subtasks

- [ ] Check and apply changes to conditional logic related to gas-based staking pools.
- [ ] Check and apply changes to components related to the gas-based staking pools. 
- [ ] Check and apply changes to stories related to the gas-based staking pools.
- [ ] Check and apply changes to unit tests related to the gas-based staking pools.
- [ ] Check and apply changes to graphQL models related to the gas-based staking pools.
- [ ] **As mentioned in the Solution block, add any not explicitly listed areas affected.**

## 🎯 Definition of Done

- [ ] There are no leftovers related to the gas-based staking pools through the code.
- [ ] No side effects to the application
  - [ ] Staking pool creation flow is not affected.
  - [ ] Staking pool management is not affected.
  - [ ] Staking pool actions deposit|stake|unstake|withdraw is not affected.
- [ ] Github action CI continue to pass.
- [ ] Vercel deploy without problem.

### PR DESCRIPTION
**Pull request by dandheedge**
Fixes #143

### CODE REVIEW

**Review by brunomenezes — CHANGES_REQUESTED** [review]
Hi @dandheedge, 
There are still some pieces of code to be cleaned. 

* GraphQL update model [here](https://github.com/cartesi/explorer/blob/refactor/143-remove-code-related-to-the-gas-based-staking-pools/apps/staking/src/graphql/models.ts#L108)
* Story [here](https://github.com/cartesi/explorer/blob/refactor/143-remove-code-related-to-the-gas-based-staking-pools/apps/staking/src/stories/pools/fee/CommissionForm.stories.tsx#L57)

I mentioned these in the issue [here](https://github.com/cartesi/explorer/issues/143#issue-1934121188)

**Review by nevendyulgerov — DISMISSED** [review]
LGTM! I just noticed a couple of messages that we may also want to remove:

- `/staking/src/utils/labels.ts` - `gasTaxCommission`
- `/staking/src/utils/messages.ts` - `messages.commission.model.gasBased`

**Comment by brunomenezes** [comment]
> LGTM! I just noticed a couple of messages that we may also want to remove:
> 
> * `/staking/src/utils/labels.ts` - `gasTaxCommission`
> * `/staking/src/utils/messages.ts` - `messages.commission.model.gasBased`

Hey @dandheedge, 
Do you mind removing these as well before we merge?

**Comment by brunomenezes** [comment]
> > LGTM! I just noticed a couple of messages that we may also want to remove:
> > 
> > * `/staking/src/utils/labels.ts` - `gasTaxCommission`
> > * `/staking/src/utils/messages.ts` - `messages.commission.model.gasBased`
> 
> Hey @dandheedge, Do you mind removing these as well before we merge?

Just giving a nudge on that before we merge cc: @dandheedge

**Comment by dandheedge** [comment]
> > > LGTM! I just noticed a couple of messages that we may also want to remove:
> > > 
> > > * `/staking/src/utils/labels.ts` - `gasTaxCommission`
> > > * `/staking/src/utils/messages.ts` - `messages.commission.model.gasBased`
> > 
> > 
> > Hey @dandheedge, Do you mind removing these as well before we merge?
> 
> Just giving a nudge on that before we merge cc: @dandheedge

@brunomenezes @nevendyulgerov already removed it

**Review by brunomenezes — APPROVED** [review]

**Pull request merged**
